CREATE TABLE users (id int, first_name varchar 128, last_name varchar 128, address varchar 128, age int);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (1, "Alex", "Karev", "613 Harper Lane Seattle, Washington", 33);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (2, "Richard", "Hendricks", "5230 Newell Road Palo Alto, California", 24);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (3, "Dinesh", "Chugati", "5230 Newell Road Palo Alto, California", 23);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (4, "Michael", "Scott", "1725 Slough Avenue Scranton, Pennsylvania", 40);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (5, "Walter", "White", "308 Negra Arroyo Lane Albuquerque, New Mexico", 50);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (6, "Jerry", "Seinfeld", "129 West 81st Street Apartment 5A New York, New York", 38);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (7, "Elaine", "Benes", "162 Riverside Drive Apartment 3E New York, New York", 36);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (8, "George", "Costanza", "129 West 81st Street Apartment 4B New York, New York", 39);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (9, "Cosmo", "Kramer", "129 West 81st Street Apartment 5B New York, New York", 41);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (10, "Newman", "Newman", "The Postal Office, New York, New York", 45);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (11, "Frank", "Costanza", "329 West 81st Street Apartment 5A New York, New York", 68);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (12, "Estelle", "Costanza", "Del Boca Vista Phase III, Florida", 65);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (13, "Jesse", "Pinkman", "9809 Margo Street Albuquerque, New Mexico", 27);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (14, "Skyler", "White", "308 Negra Arroyo Lane Albuquerque, New Mexico", 42);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (15, "Saul", "Goodman", "160 Juan Tabo Boulevard, Suite 503 Albuquerque, New Mexico", 50);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (16, "Gus", "Fring", "Los Pollos Hermanos, Albuquerque, New Mexico", 48);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (17, "Hank", "Schrader", "4901 Cumbre del Sur Court Albuquerque, New Mexico", 43);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (18, "Wendy", "S.", "Riverside Motel, Albuquerque, New Mexico", 32);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (19, "Tuco", "Salamanca", "1230 Negra Arroyo Lane Albuquerque, New Mexico", 34);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (20, "Gale", "Boetticher", "308 Negra Arroyo Lane Albuquerque, New Mexico", 32);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (21, "Badger", "Mayhew", "RV, Somewhere in the Desert", 29);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (22, "Skinny", "Pete", "Apartment 23, Albuquerque, New Mexico", 30);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (23, "Meredith", "Grey", "Grey Sloan Memorial Hospital, Seattle, Washington", 35);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (24, "Derek", "Shepherd", "Grey Sloan Memorial Hospital, Seattle, Washington", 40);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (25, "Cristina", "Yang", "1234 Chief Webber's Apartment, Seattle, Washington", 32);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (26, "Miranda", "Bailey", "Grey Sloan Memorial Hospital, Seattle, Washington", 38);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (27, "Arizona", "Robbins", "567 Surgical Wing, Grey Sloan Memorial Hospital, Seattle, Washington", 37);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (28, "Callie", "Torres", "789 Orthopedic Wing, Grey Sloan Memorial Hospital, Seattle, Washington", 36);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (29, "Mark", "Sloan", "Grey Sloan Memorial Hospital, Seattle, Washington", 40);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (30, "April", "Kepner", "1010 Mercy West Hospital, Seattle, Washington", 30);
INSERT INTO users (id, first_name, last_name, address, age) VALUES (31, "Jackson", "Avery", "678 Plastic Surgery Wing, Grey Sloan Memorial Hospital, Seattle, Washington", 34);
